{{ template "vault.mode" . }}
{{- if and (ne .mode "") (eq (.Values.global.enabled | toString) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::158869991870:role/EKSVault-David
  name: {{ template "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ end }}


# Recovery Key 1: fc4Dn2i26ckh/vBK3yKcjO6PFQrRAAPL8MaQzdgGC2Xe
# Recovery Key 2: PQRo0tKQ2xntZvVzcMxrNMmaoy5bm2Y5b71mU1brIr+6
# Recovery Key 3: jXYfPB5DoBWxqv785ejYYblV2Jbzv8wFT6PsW28mdAQl
# Recovery Key 4: GiDFCagQMobuhSl1R8XburQbLlwz6l5heph9vj3gsMyz
# Recovery Key 5: oAE18dzBYtBdJ8Tti09mN+H0RU8IdwwpOqEh0Q0q1qIy
#
# Initial Root Token: s.XlEx1AIRdM8F36usnmcScIyo
